# This workflow will run checks and validate the build

name: GoBuild

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'

    - name: Lint & Vet
      run: |
       go vet .

    - name: Validate Build
      run: go build . 
  